FROM node:14


RUN apt-get update \
    && apt-get install -y wget gnupg \
    && wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - \
    && sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' \
    && apt-get update \
    && apt-get install -y google-chrome-stable fonts-ipafont-gothic fonts-wqy-zenhei fonts-thai-tlwg fonts-kacst fonts-freefont-ttf libxss1 \
      --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*


RUN npm install -g npm@7 && npm update -g npm
WORKDIR /home/docker/code/app/
COPY package.json package-lock.json ./
RUN npm install --no-optional && npm cache clean --force
ENV PATH /home/docker/code/app/node_modules/.bin:$PATH

WORKDIR /home/docker/code/app/
COPY src ./src
